{
 "title": "NGINX Overview",
 "tags": [
  "nginx",
  "lab"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "NGINX Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "targets": [
    { "expr": "nginx_up" }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "req/s"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "active" }
   ]
  }
 ]
}